package GUI;


/*This implementation creates a `SuperManagerLoginGUI` class that 
 * allows the super manager to log in to the system and access the
 *  auto account generation subsystem.When the `SuperManagerLoginGUI` class
 *  is launched, a login panel is displayed, which prompts the super manager to enter 
 *  their username and password. If the username and password are valid, a dashboard panel 
 *  is displayed, which contains a button to access the auto account generation subsystem.
 *  When the super manager clicks on the auto account generation button, a new JFrame is displayed, 
 *  which contains a form that prompts the user to enter the necessary details such as the name 
 *  and email address of the management team member for whom the account needs to be generated.
 *   After entering the required details, the system automatically generates a unique username and 
 *   strong password for the management team member and displays it to the user in a dialog box.
 */

/*
 * The username for Supermanager is "supermanager" and password "pass123"
 */

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

import com.opencsv.CSVWriter;

public class SuperManagerWindow extends JFrame implements ActionListener {
   private JTextField usernameField;
   private JPasswordField passwordField;
   private JButton loginButton;
   private JButton generateButton;
   private JPanel dashboardPanel;
   
   public SuperManagerWindow() {
      // set up login GUI components
      usernameField = new JTextField(20);
      passwordField = new JPasswordField(20);
      loginButton = new JButton("Login");
      loginButton.addActionListener(this);
      
      // add login components to JFrame
      JPanel loginPanel = new JPanel();
      loginPanel.setLayout(new GridLayout(3, 2));
      loginPanel.add(new JLabel("Username:"));
      loginPanel.add(usernameField);
      loginPanel.add(new JLabel("Password:"));
      loginPanel.add(passwordField);
      loginPanel.add(new JLabel(""));
      loginPanel.add(loginButton);
      getContentPane().add(loginPanel);
      
      // set JFrame properties
      setTitle("Super Manager Login");
      setSize(400, 161);
      setLocationRelativeTo(null);
      setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
      setVisible(true);
   }
   
   public void actionPerformed(ActionEvent e) {
	   if (e.getSource() == loginButton) {
	      String username = usernameField.getText();
	      String password = new String(passwordField.getPassword());
	      if (username.equals("supermanager") && password.equals("pass123")) {
	         // launch dashboard GUI
	         launchDashboardGUI();
	      } else {
	         JOptionPane.showMessageDialog(null, "Invalid username or password.", "Error", JOptionPane.ERROR_MESSAGE);
	      }
	   } else if (e.getSource() == generateButton) {
	      // launch auto account generation form
	      launchAutoAccountGenerationForm();
	      
	   }
	}
   
   private void launchDashboardGUI() {
	    // remove login components from JFrame
	    getContentPane().removeAll();

	    // set up dashboard GUI components
	    JButton logoutButton = new JButton("Logout");
	    logoutButton.addActionListener(new ActionListener() {
	        public void actionPerformed(ActionEvent e) {
	            // launch management login GUI class
	            new ManagementLoginWindow();
	            dispose();  // close current JFrame
	        }
	    });
	    generateButton = new JButton("Auto Account Generation");
	    generateButton.addActionListener(this);

	    // add dashboard components to JPanel
	    dashboardPanel = new JPanel();
	    dashboardPanel.setLayout(new GridLayout(1, 2));
	    dashboardPanel.add(generateButton);
	    dashboardPanel.add(logoutButton);

	    // add JPanel to JFrame
	    getContentPane().add(dashboardPanel);

	    // resize and refresh JFrame
	    validate();
	    repaint();
	    setSize(600, 150);
	}
   private void launchAutoAccountGenerationForm() {
	   // create and set up new JFrame for form
	   JFrame frame = new JFrame("Auto Account Generation Form");
	   frame.getContentPane().setLayout(new GridLayout(3, 2));
	   frame.setSize(500, 150);
	   frame.setLocationRelativeTo(null);

	   // create form components
	   JTextField nameField = new JTextField(20);
	   nameField.setText(generateUsername());  // set autogenerated username
	   JButton generateButton = new JButton("Generate Account");
	   generateButton.addActionListener(new ActionListener() {
	      public void actionPerformed(ActionEvent e) {
	         // generate new account and write to CSV file
	         String username = nameField.getText();
	         String password = generatePassword();
	         String[] accountDetails = {username, password};
	         writeAccountToCSV(accountDetails);
	         
	         // update dashboard panel
	         dashboardPanel.remove(generateButton);
//	         JButton newGenerateButton = new JButton("Auto Account Generation");
//	         newGenerateButton.addActionListener(AdminWindow.this);
//	         dashboardPanel.add(newGenerateButton);
//	         dashboardPanel.revalidate();
//	         dashboardPanel.repaint();
	      }
	   });

	   // add components to form JFrame
	   frame.getContentPane().add(new JLabel("Username:"));
	   frame.getContentPane().add(nameField);
	   frame.getContentPane().add(new JLabel(""));
	   frame.getContentPane().add(generateButton);

	   // show form JFrame
	   frame.setVisible(true);
	}

	private String generateUsername() {
	   // generate random username
	   String characters = "abcdefghijklmnopqrstuvwxyz0123456789";
	   Random random = new Random();
	   StringBuilder username = new StringBuilder();
	   for (int i = 0; i < 5; i++) {
	      int index = random.nextInt(characters.length());
	      username.append(characters.charAt(index));
	   }
	   return username.toString();
	}
	 private void writeAccountToCSV(String[] accountDetails) {
	   String path = "../parkingManagement/CSVs/management.csv";
	   try {
	     FileWriter writer = new FileWriter(path, true);
	     CSVWriter csvWriter = new CSVWriter(writer);

	     csvWriter.writeNext(accountDetails);

	     csvWriter.close();
	     writer.close();

	     JOptionPane.showMessageDialog(null, "Account details written to CSV file.", "Account Generated", JOptionPane.INFORMATION_MESSAGE);
	   } catch (IOException e) {
	     JOptionPane.showMessageDialog(null, "Error writing account details to CSV file.", "Error", JOptionPane.ERROR_MESSAGE);
	   }
   }
   
   private String generatePassword() {
      // generate random password
     
  String lowerCase = "abcdefghijklmnopqrstuvwxyz";
  String numbers = "0123456789";
  String allCharacters =lowerCase + numbers ;
  
  Random random = new Random();
  StringBuilder password = new StringBuilder();
  
  for (int i = 0; i < 4; i++) {
     int index = random.nextInt(allCharacters.length());
     password.append(allCharacters.charAt(index));
  }
  
  return password.toString();
}

public static void main(String[] args) {
new SuperManagerWindow();
}
}